[env:esp32s3devkit]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; 编译选项
build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

; 指定源代码
src_filter = +<*>
